POWERLINE_ROOT=/usr/local/lib/python2.7/site-packages/powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. ${POWERLINE_ROOT}/bindings/bash/powerline.sh

if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

export GOPATH=$HOME/go-tools
export PATH=$PATH:$GOPATH/bin

alias docker-clear="docker rm $(docker ps -a -q)"

alias kprod="kubectl config use-context prod@us-west-2a"
alias khead="kubectl config use-context head@us-west-2a"
alias ksandbox="kubectl config use-context sandbox@us-west-2b"
alias kstaging="kubectl config use-context staging@us-west-2b"
alias ksystem="kubectl config use-context kube-system@us-west-2a"
alias kinfra="kubectl config use-context infra@us-west-2a"
alias which-kube="kubectl config view | grep current-context"

